#############################################################################
# Makefile for building: Real-Time-ALPR
# Generated by qmake (3.0) (Qt 5.0.2) on: Wed Jun 26 00:59:50 2013
# Project:  Real-Time-ALPR.pro
# Template: app
# Command: C:\Qt\Qt5.0.2\5.0.2\msvc2010\bin\qmake.exe -spec win32-msvc2010 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile Real-Time-ALPR.pro
#############################################################################

MAKEFILE      = Makefile

first: debug
install: debug-install
uninstall: debug-uninstall
QMAKE         = C:\Qt\Qt5.0.2\5.0.2\msvc2010\bin\qmake.exe
DEL_FILE      = del
CHK_DIR_EXISTS= if not exist
MKDIR         = mkdir
COPY          = copy /y
COPY_FILE     = $(COPY)
COPY_DIR      = xcopy /s /q /y /i
INSTALL_FILE  = $(COPY_FILE)
INSTALL_PROGRAM = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = del
SYMLINK       = 
DEL_DIR       = rmdir
MOVE          = move
SUBTARGETS    =  \
		debug \
		release


debug: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug
debug-make_first: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug 
debug-all: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug all
debug-clean: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug clean
debug-distclean: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug distclean
debug-install: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug install
debug-uninstall: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug uninstall
release: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release
release-make_first: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release 
release-all: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release all
release-clean: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release clean
release-distclean: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release distclean
release-install: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release install
release-uninstall: FORCE
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release uninstall

Makefile: Real-Time-ALPR.pro ..\..\mkspecs\win32-msvc2010\qmake.conf ..\..\mkspecs\features\spec_pre.prf \
		..\..\mkspecs\common\shell-win32.conf \
		..\..\mkspecs\qconfig.pri \
		..\..\mkspecs\modules\qt_lib_axbase.pri \
		..\..\mkspecs\modules\qt_lib_axcontainer.pri \
		..\..\mkspecs\modules\qt_lib_axserver.pri \
		..\..\mkspecs\modules\qt_lib_bootstrap.pri \
		..\..\mkspecs\modules\qt_lib_clucene.pri \
		..\..\mkspecs\modules\qt_lib_concurrent.pri \
		..\..\mkspecs\modules\qt_lib_core.pri \
		..\..\mkspecs\modules\qt_lib_declarative.pri \
		..\..\mkspecs\modules\qt_lib_designer.pri \
		..\..\mkspecs\modules\qt_lib_designercomponents.pri \
		..\..\mkspecs\modules\qt_lib_gui.pri \
		..\..\mkspecs\modules\qt_lib_help.pri \
		..\..\mkspecs\modules\qt_lib_multimedia.pri \
		..\..\mkspecs\modules\qt_lib_multimediawidgets.pri \
		..\..\mkspecs\modules\qt_lib_network.pri \
		..\..\mkspecs\modules\qt_lib_opengl.pri \
		..\..\mkspecs\modules\qt_lib_platformsupport.pri \
		..\..\mkspecs\modules\qt_lib_printsupport.pri \
		..\..\mkspecs\modules\qt_lib_qml.pri \
		..\..\mkspecs\modules\qt_lib_qmldevtools.pri \
		..\..\mkspecs\modules\qt_lib_qmltest.pri \
		..\..\mkspecs\modules\qt_lib_qtmultimediaquicktools.pri \
		..\..\mkspecs\modules\qt_lib_quick.pri \
		..\..\mkspecs\modules\qt_lib_quickparticles.pri \
		..\..\mkspecs\modules\qt_lib_script.pri \
		..\..\mkspecs\modules\qt_lib_scripttools.pri \
		..\..\mkspecs\modules\qt_lib_sql.pri \
		..\..\mkspecs\modules\qt_lib_svg.pri \
		..\..\mkspecs\modules\qt_lib_testlib.pri \
		..\..\mkspecs\modules\qt_lib_uitools.pri \
		..\..\mkspecs\modules\qt_lib_v8.pri \
		..\..\mkspecs\modules\qt_lib_webkit.pri \
		..\..\mkspecs\modules\qt_lib_webkitwidgets.pri \
		..\..\mkspecs\modules\qt_lib_widgets.pri \
		..\..\mkspecs\modules\qt_lib_xml.pri \
		..\..\mkspecs\modules\qt_lib_xmlpatterns.pri \
		..\..\mkspecs\features\qt_functions.prf \
		..\..\mkspecs\features\qt_config.prf \
		..\..\mkspecs\win32-msvc2010\qmake.conf \
		..\..\mkspecs\features\spec_post.prf \
		..\..\mkspecs\features\exclusive_builds.prf \
		..\..\mkspecs\features\default_pre.prf \
		..\..\mkspecs\features\win32\default_pre.prf \
		..\..\mkspecs\features\resolve_config.prf \
		..\..\mkspecs\features\default_post.prf \
		..\..\mkspecs\features\qml_debug.prf \
		..\..\mkspecs\features\declarative_debug.prf \
		..\..\mkspecs\features\win32\rtti.prf \
		..\..\mkspecs\features\warn_on.prf \
		..\..\mkspecs\features\qt.prf \
		..\..\mkspecs\features\resources.prf \
		..\..\mkspecs\features\moc.prf \
		..\..\mkspecs\features\win32\opengl.prf \
		..\..\mkspecs\features\uic.prf \
		..\..\mkspecs\features\win32\windows.prf \
		..\..\mkspecs\features\testcase_targets.prf \
		..\..\mkspecs\features\exceptions.prf \
		..\..\mkspecs\features\yacc.prf \
		..\..\mkspecs\features\lex.prf \
		Real-Time-ALPR.pro \
		C:/Qt/Qt5.0.2/5.0.2/msvc2010/lib/Qt5PrintSupport.prl \
		C:/Qt/Qt5.0.2/5.0.2/msvc2010/lib/Qt5Widgets.prl \
		C:/Qt/Qt5.0.2/5.0.2/msvc2010/lib/Qt5Gui.prl \
		C:/Qt/Qt5.0.2/5.0.2/msvc2010/lib/Qt5Core.prl \
		C:/Qt/Qt5.0.2/5.0.2/msvc2010/lib/libEGLd.prl \
		C:/Qt/Qt5.0.2/5.0.2/msvc2010/lib/libGLESv2d.prl
	$(QMAKE) -spec win32-msvc2010 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile Real-Time-ALPR.pro
..\..\mkspecs\features\spec_pre.prf:
..\..\mkspecs\common\shell-win32.conf:
..\..\mkspecs\qconfig.pri:
..\..\mkspecs\modules\qt_lib_axbase.pri:
..\..\mkspecs\modules\qt_lib_axcontainer.pri:
..\..\mkspecs\modules\qt_lib_axserver.pri:
..\..\mkspecs\modules\qt_lib_bootstrap.pri:
..\..\mkspecs\modules\qt_lib_clucene.pri:
..\..\mkspecs\modules\qt_lib_concurrent.pri:
..\..\mkspecs\modules\qt_lib_core.pri:
..\..\mkspecs\modules\qt_lib_declarative.pri:
..\..\mkspecs\modules\qt_lib_designer.pri:
..\..\mkspecs\modules\qt_lib_designercomponents.pri:
..\..\mkspecs\modules\qt_lib_gui.pri:
..\..\mkspecs\modules\qt_lib_help.pri:
..\..\mkspecs\modules\qt_lib_multimedia.pri:
..\..\mkspecs\modules\qt_lib_multimediawidgets.pri:
..\..\mkspecs\modules\qt_lib_network.pri:
..\..\mkspecs\modules\qt_lib_opengl.pri:
..\..\mkspecs\modules\qt_lib_platformsupport.pri:
..\..\mkspecs\modules\qt_lib_printsupport.pri:
..\..\mkspecs\modules\qt_lib_qml.pri:
..\..\mkspecs\modules\qt_lib_qmldevtools.pri:
..\..\mkspecs\modules\qt_lib_qmltest.pri:
..\..\mkspecs\modules\qt_lib_qtmultimediaquicktools.pri:
..\..\mkspecs\modules\qt_lib_quick.pri:
..\..\mkspecs\modules\qt_lib_quickparticles.pri:
..\..\mkspecs\modules\qt_lib_script.pri:
..\..\mkspecs\modules\qt_lib_scripttools.pri:
..\..\mkspecs\modules\qt_lib_sql.pri:
..\..\mkspecs\modules\qt_lib_svg.pri:
..\..\mkspecs\modules\qt_lib_testlib.pri:
..\..\mkspecs\modules\qt_lib_uitools.pri:
..\..\mkspecs\modules\qt_lib_v8.pri:
..\..\mkspecs\modules\qt_lib_webkit.pri:
..\..\mkspecs\modules\qt_lib_webkitwidgets.pri:
..\..\mkspecs\modules\qt_lib_widgets.pri:
..\..\mkspecs\modules\qt_lib_xml.pri:
..\..\mkspecs\modules\qt_lib_xmlpatterns.pri:
..\..\mkspecs\features\qt_functions.prf:
..\..\mkspecs\features\qt_config.prf:
..\..\mkspecs\win32-msvc2010\qmake.conf:
..\..\mkspecs\features\spec_post.prf:
..\..\mkspecs\features\exclusive_builds.prf:
..\..\mkspecs\features\default_pre.prf:
..\..\mkspecs\features\win32\default_pre.prf:
..\..\mkspecs\features\resolve_config.prf:
..\..\mkspecs\features\default_post.prf:
..\..\mkspecs\features\qml_debug.prf:
..\..\mkspecs\features\declarative_debug.prf:
..\..\mkspecs\features\win32\rtti.prf:
..\..\mkspecs\features\warn_on.prf:
..\..\mkspecs\features\qt.prf:
..\..\mkspecs\features\resources.prf:
..\..\mkspecs\features\moc.prf:
..\..\mkspecs\features\win32\opengl.prf:
..\..\mkspecs\features\uic.prf:
..\..\mkspecs\features\win32\windows.prf:
..\..\mkspecs\features\testcase_targets.prf:
..\..\mkspecs\features\exceptions.prf:
..\..\mkspecs\features\yacc.prf:
..\..\mkspecs\features\lex.prf:
Real-Time-ALPR.pro:
C:/Qt/Qt5.0.2/5.0.2/msvc2010/lib/Qt5PrintSupport.prl:
C:/Qt/Qt5.0.2/5.0.2/msvc2010/lib/Qt5Widgets.prl:
C:/Qt/Qt5.0.2/5.0.2/msvc2010/lib/Qt5Gui.prl:
C:/Qt/Qt5.0.2/5.0.2/msvc2010/lib/Qt5Core.prl:
C:/Qt/Qt5.0.2/5.0.2/msvc2010/lib/libEGLd.prl:
C:/Qt/Qt5.0.2/5.0.2/msvc2010/lib/libGLESv2d.prl:
qmake: FORCE
	@$(QMAKE) -spec win32-msvc2010 CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile Real-Time-ALPR.pro

qmake_all: FORCE

make_first: debug-make_first release-make_first FORCE
all: debug-all release-all FORCE
clean: debug-clean release-clean FORCE
	-$(DEL_FILE) Real-Time-ALPR.exp
	-$(DEL_FILE) Real-Time-ALPR.ilk
	-$(DEL_FILE) vc*.pdb
	-$(DEL_FILE) vc*.idb
distclean: debug-distclean release-distclean FORCE
	-$(DEL_FILE) Makefile
	-$(DEL_FILE) Real-Time-ALPR.pdb

debug-mocclean:
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug mocclean
release-mocclean:
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release mocclean
mocclean: debug-mocclean release-mocclean

debug-mocables:
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Debug mocables
release-mocables:
	@set MAKEFLAGS=$(MAKEFLAGS)
	$(MAKE) -f $(MAKEFILE).Release mocables
mocables: debug-mocables release-mocables

check: first
FORCE:

$(MAKEFILE).Debug: Makefile
$(MAKEFILE).Release: Makefile
